services:
  - type: web
    name: gambo
    env: node
    plan: starter
    buildCommand: npm install && npm run build && npx prisma generate && npx prisma migrate deploy
    startCommand: npm run start:production
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: BETSAPI_SOCCER_TOKEN
        sync: false
      - key: BETSAPI_BASKETBALL_TOKEN
        sync: false
      - key: BETSAPI_TENNIS_TOKEN
        sync: false
      - key: BETSAPI_HOCKEY_TOKEN
        sync: false
      - key: BETSAPI_FOOTBALL_TOKEN
        sync: false
